---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 0
  strategy:
    type:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: "atanu92/webapp:latest"
        name: webapp
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 5000
  selector:
    app: webapp
  type: LoadBalancer