apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
#  strategy:
#    type:
#    rollingUpdate:
#      maxUnavailable: 0
#      maxSurge: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: "atanu92/webapp:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
    targetPort: 8000
  selector:
    app: webapp
  type: LoadBalancer